site/app.py
# Imports
from flask import Flask
from modules import db

try:
    from dotenv import dotenv_values, load_dotenv
    dotenv_exists = True
except:
    # error only raised if project is in production
    dotenv_exists = False
from routes import routes
import os

# App initialization
app = Flask(__name__, static_folder='static', template_folder='templates')

# App Config initialization
if dotenv_exists:
    load_dotenv(".env")
    app.config.from_mapping(dotenv_values())
    app.config["TESTING"] = True
    app.config["DEBUG"] = True
else:
    app.config.from_mapping(os.environ)
    
# Database initialization
db.init_app(app)

# Blueprint registrations
app.register_blueprint(routes)

if __name__ == '__main__':
    app.run()

site/routes.py
# Imports
from flask import (
    Blueprint, render_template, request, jsonify,
    url_for
)
from config import getconfig
from itsdangerous import URLSafeTimedSerializer
from itsdangerous.exc import SignatureExpired


# Routes Blueprint and initializations
routes = Blueprint("routes", __name__, template_folder='templates', static_folder='static')
api = Blueprint("api", __name__, template_folder='templates', static_folder='static', url_prefix='/api')
routes.register_blueprint(api)

# Blueprint records
@routes.record
def serializer(setup_state):
    app = setup_state.app
    with app.app_context():
        api.serializer = URLSafeTimedSerializer(getconfig("SECRET_KEY"), getconfig("SERIALIZER_SALT"))

# Public Routes
@routes.route("/", methods=['GET', 'POST'])
def index():
    # more should/will be added here as project progresses
    return render_template("index.html")

@routes.route("/tos", methods=['GET'])
def tos():
    return render_template("terms.html")

@routes.route("/signin", methods=['GET', 'POST'])
def signin():
    # more should/will be added here as project progresses
    return render_template("auth/signin.html")


@routes.route("/register", methods=['GET', 'POST'])
def register():
    # more should/will be added here as project progresses
    return render_template("auth/register.html")


@routes.route("/editor/edit", methods=['GET', 'POST'])
def edit_editor():
    # more should/will be added here as project progresses
    return render_template("editor/editor.html", new=False)

@routes.route("/editor/new", methods=['GET', 'POST'])
def new_editor():
    # more should/will be added here as project progresses
    return render_template("editor/editor.html", new=True)

# api routes
@api.route("/forgotpwd", methods=['POST'])
def forgotpwd():

    data = request.get_json()
    res_type = "success"
    base_url = f"{url_for('routes.api.accountapimanager', type='forgot')}&s="
    
    # validation goes here
    email = data["email"]
    
    # generate token    
    try:
        token = api.serializer.dumps(email)
    except Exception:
        res_type = "error"
        token = None
        
    url = base_url + str(token)
    
    res = {
        "type" : res_type,
        "forgot_url": url
        }
    
    return jsonify(res)


@api.route("/accmanager", methods=['GET', 'POST'])
def accountapimanager():
    if request.args:
        args = request.args.to_dict()
        type = args.get("type") # checks for the required type parameter
        
        if type == 'forgot':
            token = args["s"]
            print("Serialized email: ", token)
            
            try:
                email = api.serializer.loads(token, max_age=60*3) # 60 * 3 will give 3 minutes in durations of seconds
            except SignatureExpired:
                # Will set a error message page here
                return render_template("accmanager/forgot/expired.html")
            print("Deserialized email: ", email)
            return "", 200
    return "", 403 # Access Forbidden


@api.route("/drawobj/<type>", methods=['POST'])
def drawobj(type):
    if request.args:
        return "", 200
    return "", 403

site/templates/accmanager/confirm/confirmacc.html
{% extends "./layout/layout.html" %}

site/templates/accmanager/forgot/expired.html
{% extends "./layout/layout.html" %}
{% block body %}
<div class="container mx-auto">
    <div class="flex flex-col w-1/2 p-3 mx-auto text-base bg-red-200 font-ptsans my-1/2 h-1/2">
        <h2 class="text-lg text-red-600">Token Expired</h2>
        <p class="text-red-400">
            You took too long to click on the link. If you still need to reset your password, go back to the login page and start over
            <div class="mt-3">
                <a href="/" class="text-red-600 hover:text-red-800">Go Back to Home</a>
            </div>
        </p>
    </div>
</div>
{% endblock %}

site/templates/accmanager/forgot/pwdreset.html
{% extends "./layout/layout.html" %}

site/templates/layout/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="author" content="Sergio Ley Languren" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />
        <link href="{{ url_for('static', filename='dist/css/source.min.css') }}" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="{{ url_for('static', filename='node_modules/flowbite/dist/flowbite.min.js') }}"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,530;1,530&family=PT+Sans&display=swap" rel="stylesheet">
        <title>PenFlow</title>
        {% block style %}{% endblock %}
    </head>
    <body>
        <div class="container mx-auto">
            <div id="head" class="p-[0.15rem] mb-3">
                <span class="flex items-center h-20 p-4 text-4xl subpixel-antialiased text-white box-decoration-slice bg-gradient-to-l from-sky-500 to-fuchsia-500
  font-dancing sm1xs:text-2xl tracking-wider
">
                    Penflow Note Taking
                </span>
                <nav class="bg-slate-50 border-slate-50">
                    <div class="flex flex-wrap items-center justify-between p-4 mx-auto max-w-screen-xl">
                        <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
                            <span class="self-center text-2xl font-semibold whitespace-nowrap"><i class="fa-regular fa-compass"></i> Menu</span>
                        </a>
                        <button data-collapse-toggle="penflow-navbar" type="button" class="inline-flex items-center justify-center w-10 h-10 p-2 text-sm text-slate-200 rounded-lg
  md:hidden hover:bg-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-400" aria-controls="penflow-navbar" aria-expanded="false">
                            <span class="sr-only">Open main menu</span>
                            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                            </svg>
                        </button>
                        <div class="hidden w-full md:block md:w-auto" id="penflow-navbar">
                            <ul class="flex flex-col p-4 mt-4 font-medium border rounded-lg md:p-0 border-slate-200 bg-slate-100 md:bg-slate-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
                              <li>
                                <a href="/" class="block px-3 py-2 rounded text-slate-400 bg-slate-100 md:bg-slate-50 md:hover:text-slate-700 md:p-0" aria-current="page">Home</a>
                              </li>
                              <li>
                                <button id="accountNavbarLink" data-dropdown-toggle="accountNavbar" class="flex items-center justify-between w-full px-3 py-2 rounded text-slate-400 hover:bg-gray-100 
  md:hover:bg-transparent md:border-0 md:hover:text-slate-700 md:p-0 md:w-auto">
                                    Account
                                    <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                                    </svg>
                                </button>
                                <!-- Dropdown menu -->
                                <div id="accountNavbar" class="z-10 hidden font-normal bg-white rounded-lg shadow divide-y divide-gray-100 w-44">
                                    <ul class="py-2 text-sm text-slate-400" aria-labelledby="dropdownLargeButton">
                                        <!-- TODO: Check will be implemented to check if the current user is signed in and if so, remove the login option -->
                                        <li>
                                            <a href="{{ url_for('routes.signin') }}" class="block px-4 py-2 hover:bg-slate-200">Login</a>
                                        </li>
                                        <!-- TODO: Check will be implemented to check if the current user is signed out and if so, offer a Register option -->
                                        <li>
                                            <a href="{{ url_for('routes.register') }}" class="block px-4 py-2 hover:bg-slate-200">Register</a>
                                        </li>
                                        <!-- TODO: Check will be implemented to check if the current user is signed in and if so, offer a Settings option -->
                                        <li>
                                            <a href="#" class="block px-4 py-2 hover:bg-slate-200">Settings</a>
                                        </li>
                                    </ul>
                                    <!-- TODO: Check will be implemented to check if current user is signed in and if so, present the Sign out option -->
                                    <div class="py-1">
                                        <a href="#" class="block px-4 py-2 text-sm text-slate-400 hover:bg-slate-200">Sign out</a>
                                    </div>
                                </div>
                              </li>
                            </ul>
                          </div>
                    </div>
                </nav>
            </div>
            {% block body %}{% endblock %}
        </div>
        {% block scripts %}{% endblock %}
    </body>
</html>

site/templates/terms.html
{% extends './layout/layout.html' %}
{% block body %}
<div class="container mx-auto">
    <h3 class="mb-2 text-2xl font-notoserif">Terms of Service</h3>
    <hr class="mb-2" />
    <p class="font-ptsans">
        1. Acceptance of Terms <br>
        By accessing and using this website, you agree to be bound by these terms and conditions. If you do not agree with any of these terms, please do not use this website.
        <div class="mb-3"></div>
        2. Intellectual Property <br>
        All content on this website, including but not limited to text, graphics, logos, images, and software, is the property of <i>PenFlow</i> and is protected by intellectual property laws. You may not use, reproduce, or distribute any content from this website without prior written permission.
        <div class="mb-3"></div>
        3. Disclaimer of Liability <br>
        <i>PenFlow</i> makes no representations or warranties of any kind, express or implied, regarding the accuracy, reliability, or completeness of the information on this website. You agree that your use of this website is at your own risk.
        <div class="mb-3"></div>
        4. Governing Law <br>
        These terms and conditions shall be governed by and construed in accordance with the laws of the United States and of your own state. Any disputes arising out of or in connection with these terms and conditions shall be subject to the exclusive jurisdiction of the courts of the United States and of your own state.
        <div class="mb-3"></div>
        5. Modifications <br>
        <i>PenFlow</i> reserves the right to modify these terms and conditions at any time without prior notice. By continuing to use this website after any changes are made, you agree to be bound by the updated terms and conditions.
        <div class="mb-3"></div>
        6. Contact Information <br>
        If you have any questions or concerns about these terms and conditions, please contact us at <a href="mailto:penflow2@gmail.com" class="text-sky-400 hover:text-sky-500">penflow2@gmail.com</a>.
        <div class="mb-3"></div>
        7. Severability <br>
        If any provision of these terms and conditions is found to be invalid or unenforceable, the remaining provisions shall still be valid and enforceable to the fullest extent permitted by law.
        <div class="mb-3"></div>
        8. Entire Agreement <br>
        These terms and conditions constitute the entire agreement between you and <i>PenFlow</i> regarding your use of this website and supersede all prior agreements and understandings.
        <div class="mb-3"></div>
        9.  Waiver <br>
        The failure of <i>PenFlow</i> to enforce any provision of these terms and conditions shall not be deemed as a waiver of such provision or the right to enforce it.
        <div class="mb-3"></div>
        10.  Assignment <br>
        You may not assign, transfer, or sublicense any of your rights or obligations under these terms and conditions without the prior written consent of <i>PenFlow</i>.
        <div class="mb-3"></div>
        12.  Updates to the Terms and Conditions <br>
        <i>PenFlow</i> reserves the right to update or change these terms and conditions at any time. Any updates or changes will be effective immediately upon posting on this website.
        <div class="mb-3"></div>
    </p>
</div>
{% endblock %}